# flask
ENV: production
DEBUG: True

# swagger
SWAGGER:
  title: binance trading API
  version: 0.0.1
  uiversion: 3
  openapi: 3.0.0
  static_url_path: /flasgger_static
  swagger_ui: True
  specs_route: /apidocs/

# binance api
binance:
  api_key: s3ibT86bILkqjwdaQHJCR9S0JAiOSX6DgZsuMtvOcNAezsuo7KXbmWt11uJ0Pfys
  api_secret: 5EzacPxveeGaBLC89FPsZ6Yi4NG1ekcaDP1nWtpTyZtD1wSvBRyLVZS1MNHzyyKI